{"name": "Check login page open successfully", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x002A9943+2595139]\n\tOrdinal0 [0x0023C9F1+2148849]\n\tOrdinal0 [0x001343F0+1065968]\n\tOrdinal0 [0x00155D5D+1203549]\n\tOrdinal0 [0x00156F96+1208214]\n\tGetHandleVerifier [0x0044B232+1658114]\n\tGetHandleVerifier [0x0050312C+2411516]\n\tGetHandleVerifier [0x0033F261+560433]\n\tGetHandleVerifier [0x0033E366+556598]\n\tOrdinal0 [0x0024286B+2173035]\n\tOrdinal0 [0x002475F8+2192888]\n\tOrdinal0 [0x002476E5+2193125]\n\tOrdinal0 [0x002511FC+2232828]\n\tBaseThreadInitThunk [0x7630FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77A67A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77A67A6E+238]\n\t(No symbol) [0x00000000]\n\n", "trace": "  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\loginSteps.py\", line 79, in closeBrowser\n    context.driver.close()\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given browser is open", "status": "passed", "start": 1648202344864, "stop": 1648202347320}, {"name": "When user is on login page", "status": "passed", "start": 1648202347320, "stop": 1648202360323}, {"name": "And user enter username", "status": "passed", "start": 1648202360324, "stop": 1648202360439}, {"name": "And Click on the continue button", "status": "passed", "start": 1648202360439, "stop": 1648202361452}, {"name": "Then user enter password", "status": "passed", "start": 1648202361452, "stop": 1648202366538}, {"name": "And Click on the submit button", "status": "passed", "start": 1648202366538, "stop": 1648202373649}, {"name": "And user navigated to home page", "status": "passed", "start": 1648202373649, "stop": 1648202373889}, {"name": "Then close browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x002A9943+2595139]\n\tOrdinal0 [0x0023C9F1+2148849]\n\tOrdinal0 [0x001343F0+1065968]\n\tOrdinal0 [0x00155D5D+1203549]\n\tOrdinal0 [0x00156F96+1208214]\n\tGetHandleVerifier [0x0044B232+1658114]\n\tGetHandleVerifier [0x0050312C+2411516]\n\tGetHandleVerifier [0x0033F261+560433]\n\tGetHandleVerifier [0x0033E366+556598]\n\tOrdinal0 [0x0024286B+2173035]\n\tOrdinal0 [0x002475F8+2192888]\n\tOrdinal0 [0x002476E5+2193125]\n\tOrdinal0 [0x002511FC+2232828]\n\tBaseThreadInitThunk [0x7630FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77A67A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77A67A6E+238]\n\t(No symbol) [0x00000000]\n\n", "trace": "  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\loginSteps.py\", line 79, in closeBrowser\n    context.driver.close()\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in close\n    self.execute(Command.CLOSE)\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\ishwari.khismatrao\\pycharmprojects\\pythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1648202373889, "stop": 1648202374023}], "start": 1648202344861, "stop": 1648202374024, "uuid": "4550a7a7-ed87-411b-9243-0864d201186c", "historyId": "24d5a72ea2ecb979cf192d0aa4afd7ba", "fullName": "Check login is successful with valid credentials: Check login page open successfully", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Check login is successful with valid credentials"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}